app:
  name: Codly
  port: 8080
database:
  host: "192.168.2.10"
  port: 3306
  username: "codly_test"
  password: "123456"
  db_name: "codly_test_db"
bcrypt_password: p@ssword
jwt_secret_key: my_secret_key